# fly.toml app configuration file generated for chick-chuck on 2023-06-07T10:54:59+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chick-chuck"
primary_region = "mad"
console_command = "/rails/bin/rails console"

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
      hard_limit = 25
      soft_limit = 20
      type = "connections"
  
  [[http_service.ports]]
    force_https = true
    handlers = ["http"]
    port = 3000
      
  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
