# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/companies/trucks', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Carriers::Truck. As you add validations to Carriers::Truck, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Companies::Truck.create! valid_attributes
      get companies_trucks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      truck = Companies::Truck.create! valid_attributes
      get companies_truck_url(truck)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_companies_truck_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      truck = Companies::Truck.create! valid_attributes
      get edit_companies_truck_url(truck)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Carriers::Truck' do
        expect do
          post companies_trucks_url, params: { company_truck: valid_attributes }
        end.to change(Companies::Truck, :count).by(1)
      end

      it 'redirects to the created companies_truck' do
        post companies_trucks_url, params: { company_truck: valid_attributes }
        expect(response).to redirect_to(companies_truck_url(Carriers::Truck.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Carriers::Truck' do
        expect do
          post companies_trucks_url, params: { company_truck: invalid_attributes }
        end.to change(Companies::Truck, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post companies_trucks_url, params: { company_truck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested companies_truck' do
        truck = Companies::Truck.create! valid_attributes
        patch companies_truck_url(truck), params: { company_truck: new_attributes }
        truck.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the companies_truck' do
        truck = Companies::Truck.create! valid_attributes
        patch companies_truck_url(truck), params: { company_truck: new_attributes }
        truck.reload
        expect(response).to redirect_to(companies_truck_url(truck))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        truck = Companies::Truck.create! valid_attributes
        patch companies_truck_url(truck), params: { company_truck: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested companies_truck' do
      truck = Companies::Truck.create! valid_attributes
      expect do
        delete companies_truck_url(truck)
      end.to change(Companies::Truck, :count).by(-1)
    end

    it 'redirects to the companies_trucks list' do
      truck = Companies::Truck.create! valid_attributes
      delete companies_truck_url(truck)
      expect(response).to redirect_to(companies_trucks_url)
    end
  end
end
